#version: "3.8"
services:
  db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - .env
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    container_name: app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TRUST_SERVER_CERTIFICATE=true
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: app-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sql_data:
